### ISSUE TITLE
use requestAnimationFrame for smoother re-paints

### ISSUE THREAD

**Issue by mozfreddyb** [coolwanglu/BrowserHack#11]
Using [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) for calls to functions like `recenter_map` could help improving repaint performance

**Comment by coolwanglu** [comment]
I wonder if you have test it. I remembered that `recenter_map` is not called frequently (with different center positions)

**Comment by coolwanglu** [comment]
If I understand correctly, `requestAnimationFrame` is useful for functions that's called as fast as 60fps, right? But `recenter_map` should be only called (a few times) between user inputs.
