### ISSUE TITLE
How can you kick?

### ISSUE THREAD

**Issue by ghost** [coolwanglu/BrowserHack#12]
Control-d is supposed to be kick, but in a browser, that bookmarks. There's no #kick extended command either.  Thus kicking a sink, or a locked door, or a chest, or a monster, or even the wall if you're so inclined -- all these are impossible?

**Comment by coolwanglu** [comment]
It's known that `^D` does not work on IE/Chrome + Windows. It should work on other browser+OS.

Will fix it soon.

**Comment by coolwanglu** [comment]
For now, there are 2 workarounds:
- Use `number_pad`, then `k` is for kicking
- Click on the door with your mouse

**Comment by ghost** [comment]
Thanks

**Comment by coolwanglu** [comment]
Fixed. Please reload the page and have a try.
