### ISSUE TITLE
On reload inventory is full of "strange object"

### ISSUE THREAD

**Issue by phs** [coolwanglu/BrowserHack#13]
Upon restoring my game (after ending the session with `S` save), my inventory seems to be in a strange state.  None of the objects have retained their names in the inventory hover text on the right.  Several objects are now `strange object`, but other bizarre names appear as well (`(null)`, or merely the empty string.)

The state of what is currently worn and/or equipped appears corrupted as well.  A cloak of invisibility appears unequipped, though it was on save and still seemingly renders me invisible on load.  A scroll appears to be confused with my throwing daggers, sharing their name and a place in my quiver.

Some screen shots:
![screen-shot](https://cloud.githubusercontent.com/assets/36229/8273601/270a893a-182a-11e5-8502-3339683f3660.png)

![boots-of-hmm](https://cloud.githubusercontent.com/assets/36229/8273604/371b6e48-182a-11e5-9a49-f94ab2187ddb.png)

![quivered-scroll-of-hmm](https://cloud.githubusercontent.com/assets/36229/8273606/3f0890d6-182a-11e5-93ed-1518883d425f.png)

![null-spellbook](https://cloud.githubusercontent.com/assets/36229/8273607/448c2b6c-182a-11e5-8412-c879aee8d510.png)

![blank-potion](https://cloud.githubusercontent.com/assets/36229/8273608/4c0a6e6c-182a-11e5-9b41-61afc6a9653f.png)

Some other observations:
- The inventory icons themselves are still correct
- The assigned keyboard (`#adjust`) letters are still correct
- The placement of the items in the different sections of the inventory is still correct.
- This isn't the first time I've saved and loaded this character, but it is the first time I've seen the odd behavior.

I can try to conjure up the IndexedDB if you think that'll help, but there doesn't appear to be an easy export option.

Chrome 43.0.2357.124 (64-bit) on OSX 10.10

**Comment by phs** [comment]
One more data point: other inventory selection interfaces (like `D` dropping multiple items) seems almost fine.

![drop-selection-still-fine](https://cloud.githubusercontent.com/assets/36229/8273653/12d324c0-182c-11e5-95a0-c829d62ae718.png)

I say "almost" since it appears the spellbook is now gold (I don't recall what it was before saving, since it is recent loot.  However the icon disagrees with the inventory sidebar.)

![gold-spellbook](https://cloud.githubusercontent.com/assets/36229/8273680/92ade0fe-182c-11e5-80ac-5f9bf0998edd.png)

**Comment by phs** [comment]
..and upon dropping most things onto that altar, the labels in the inventory have fixed themselves.  So, no worries ^_^ (also: fun port!)

**Comment by coolwanglu** [comment]
Yes, it actually takes longer than I had thought before there is a report.

Currently the inventory sidebar is only updated when your inventory is changed. You can press `i` to update it.

I'll try to fix it by forcing update it right after loading a game.

**Comment by phs** [comment]
I can confirm that pressing `i` on reload fixes it immediately.
