### ISSUE TITLE
Overlay menus with item listings do not show item ID nor respond to keys

### ISSUE THREAD

**Issue by joshuaeckroth** [coolwanglu/BrowserHack#2]
E.g., press W to wear something, then press ? to see the list of things that can be worn. This overlay list does not show the item ID (A-Z, a-z). Furthermore, pressing a-z or whatever does nothing if the overlay is shown.

A correct fix would be to show the item IDs and allow pressing a key to indicate which item(s) you want.

**Comment by coolwanglu** [comment]
Right. I was actually rushing to make everything (basically) works, will improve the UI from now on.

**Comment by coolwanglu** [comment]
It's done :)
