### ISSUE TITLE
Firefox suggests asynchronous scripts

### ISSUE THREAD

**Issue by freddyb** [coolwanglu/BrowserHack#5]
I get this in the error console

> Successfully compiled asm.js code (total compilation time 29ms; unable to cache asm.js in synchronous scripts; try loading asm.js via <script async> or createElement('script'))

It seems this can be fixed by tagging the script tags with the `async` attribute. The longer explanation is on MDN: https://developer.mozilla.org/en-US/docs/Games/Techniques/Async_scripts

**Comment by coolwanglu** [comment]
Fixed in git. Thanks.
