### ISSUE TITLE
"Cannot sync fs, savegame may not work!"

### ISSUE THREAD

**Issue by freddyb** [coolwanglu/BrowserHack#6]
I get this in the browser developer tools console and indeed, saving games does not work.

**Comment by coolwanglu** [comment]
What's your browser and OS? IndexDB must be supported for savegame.

**Comment by freddyb** [comment]
I am on Firefox Deveolper Edition (currently Firefox 39).
IndexedDB works fine on other pages :-)

**Comment by coolwanglu** [comment]
I see. Did you see this message right after starting the game, or after saving the game?

**Comment by freddyb** [comment]
For some reason, I stopped seeing this error and Save/Load works for me. Sweet.

**Comment by coolwanglu** [comment]
I think I found this issue before, but cannot reproduce it now.

**Comment by coolwanglu** [comment]
Maybe we can reopen this when we can consistently reproduce it.
