### ISSUE TITLE
Cannot assign class, gender, alignment during startup

### ISSUE THREAD

**Issue by freddyb** [coolwanglu/BrowserHack#7]
It just asks for a name and then picks class, gender and alignment randomly.

**Comment by freddyb** [comment]
(Btw your work on this is top-notch. Please don't take the issues I file as criticism:))

**Comment by coolwanglu** [comment]
Issues are welcome :)

Yes, I have not implemented it yet.

**Comment by coolwanglu** [comment]
Done.
